import { mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import {
  BASELINE_INSTANCE_ID,
  LEGACY_PACKAGE_NAME,
  LEGACY_USER_INSTANCE_ID,
  PACKAGE_NAME,
  PREVIOUS_PACKAGE_NAME,
  PREVIOUS_USER_INSTANCE_ID,
  PROVIDER_CLOUDFLARE,
  PROVIDER_TAILSCALE,
  USER_INSTANCE_ID,
} from '../core/constants.mjs'
import { assertSafeConfig } from '../core/config.mjs'

function yamlQuote(value) {
  return `'${String(value).replaceAll("'", "''")}'`
}

function yamlList(values, indent) {
  return values.map(value => `${indent}- ${yamlQuote(value)}`).join('\n')
}

function userProvider(provider) {
  if (provider.type === PROVIDER_CLOUDFLARE) {
    return {
      type: provider.type,
      routeManagement: provider.routeManagement,
      teamOrigin: provider.teamOrigin,
      applicationAudience: provider.applicationAudience,
    }
  }
  return {
    type: provider.type,
    routeManagement: provider.routeManagement,
  }
}

function userAuth(auth) {
  const next = {
    mode: auth.mode,
    trustedPrincipals: [...auth.trustedPrincipals],
  }
  if (auth.credentialStorePath) next.credentialStorePath = auth.credentialStorePath
  return next
}

export function renderProfileEntry(config) {
  const user = {
    enabled: true,
    externalOrigin: config.externalOrigin,
    provider: userProvider(config.provider),
    auth: userAuth(config.auth),
    ...(config.activationToken ? { activationToken: config.activationToken } : {}),
  }
  const safe = assertSafeConfig(user)
  if (!safe.enabled) throw new Error('dsh-one-gateway: setup cannot write a disabled profile entry')
  const lines = [
    '# Generated by dsh-one-gateway setup. Edit trustedPrincipals to add or remove operators.',
    '# Restart the DSH Web process you own after setup so it loads this inserted instance.',
    '- insert:',
    `    - id: ${USER_INSTANCE_ID}`,
    `      name: ${PACKAGE_NAME}`,
    '      config:',
    '        enabled: true',
    `        externalOrigin: ${yamlQuote(safe.externalOrigin)}`,
    '        provider:',
    `          type: ${safe.provider.type}`,
    `          routeManagement: ${safe.provider.routeManagement}`,
  ]
  if (safe.provider.type === PROVIDER_CLOUDFLARE) {
    lines.push(`          teamOrigin: ${yamlQuote(safe.provider.teamOrigin)}`)
    lines.push(`          applicationAudience: ${yamlQuote(safe.provider.applicationAudience)}`)
  }
  lines.push('        auth:')
  lines.push(`          mode: ${safe.auth.mode}`)
  lines.push('          trustedPrincipals:')
  lines.push(yamlList(safe.auth.trustedPrincipals, '            '))
  if (safe.activationToken) {
    lines.push(`        activationToken: ${yamlQuote(safe.activationToken)}`)
  }
  lines.push('')
  return lines.join('\n')
}

export function hasGatewayProfileEntry(profile) {
  const names = [
    PACKAGE_NAME,
    USER_INSTANCE_ID,
    BASELINE_INSTANCE_ID,
    PREVIOUS_PACKAGE_NAME,
    PREVIOUS_USER_INSTANCE_ID,
    LEGACY_PACKAGE_NAME,
    LEGACY_USER_INSTANCE_ID,
  ]
  const escaped = names.map(name => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')
  const pattern = new RegExp(`^\\s*(?:-\\s+)?(?:id|name)\\s*:\\s*['"]?(?:${escaped})['"]?\\s*(?:#.*)?$`, 'm')
  return pattern.test(profile)
}

export function appendProfileEntry(existing, entry) {
  if (hasGatewayProfileEntry(existing)) {
    throw new Error('a dsh-one-gateway, dsh-gateway, or dsh-tailscale-gateway profile entry already exists; edit or remove that existing entry instead')
  }
  const meaningful = existing.split(/\r?\n/).find(line => line.trim() !== '' && !line.trimStart().startsWith('#'))
  if (meaningful !== undefined && meaningful.trim() !== '[]' && !/^\s*-\s+/.test(meaningful)) {
    throw new Error('the DSH Web profile override is not a top-level YAML list; refusing to modify it')
  }
  const base = meaningful?.trim() === '[]'
    ? existing.replace(/(?:^|\r?\n)\s*\[\]\s*$/, '')
    : existing
  return `${base.replace(/\s*$/, '')}${base.trim() === '' ? '' : '\n\n'}${entry}`
}

export async function writeInitialProfileEntry(profilePath, entry, fs = { mkdir, readFile, rename, stat, writeFile }) {
  let existing = ''
  let existingMode = 0o600
  try {
    existing = await fs.readFile(profilePath, 'utf8')
    existingMode = (await fs.stat(profilePath)).mode & 0o777
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error
  }
  const updated = appendProfileEntry(existing, entry)
  const directory = dirname(profilePath)
  await fs.mkdir(directory, { recursive: true, mode: 0o700 })
  const temporary = `${profilePath}.dsh-one-gateway-${process.pid}.tmp`
  await fs.writeFile(temporary, updated, { encoding: 'utf8', mode: existingMode || 0o600 })
  await fs.rename(temporary, profilePath)
  return Object.freeze({ created: existing === '', profilePath })
}

export { USER_INSTANCE_ID, PACKAGE_NAME, BASELINE_INSTANCE_ID, PROVIDER_TAILSCALE }
