import {
  AUTH_GATEWAY_CREDENTIAL,
  AUTH_SIGNED_JWT,
  AUTH_TRUSTED_HEADER,
  COMPATIBILITY,
  GATEWAY_HOST,
  GATEWAY_PORT,
  MAX_PRINCIPAL_LENGTH,
  MAX_TRUSTED_PRINCIPALS,
  PROVIDER_CLOUDFLARE,
  PROVIDER_EASYTIER,
  PROVIDER_TAILSCALE,
  READINESS_PATH,
  ROUTE_ENSURE,
  ROUTE_VERIFY_ONLY,
  UPSTREAM_HOST,
  UPSTREAM_PORT,
} from './constants.mjs'
import { httpsPortFromOrigin } from './origin.mjs'

const ENABLED_KEYS = new Set(['enabled', 'externalOrigin', 'provider', 'auth', 'activationToken'])
const FORBIDDEN_KEYS = new Set([
  'listenHost', 'listenPort', 'upstream', 'headerName', 'jwksUrl',
  'allowAnonymous', 'trustPrivateNetwork', 'public', 'funnel', 'publicOrigin',
  'tls', 'trustedLogins', 'tailscaleServe',
])
const TAILSCALE_PROVIDER_KEYS = new Set(['type', 'routeManagement'])
const CLOUDFLARE_PROVIDER_KEYS = new Set(['type', 'routeManagement', 'teamOrigin', 'applicationAudience'])
const AUTH_COMMON_KEYS = new Set(['mode', 'trustedPrincipals'])
const AUTH_CREDENTIAL_KEYS = new Set(['mode', 'trustedPrincipals', 'credentialStorePath'])

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function rejectForbiddenKeys(object, label) {
  for (const key of Object.keys(object)) {
    if (FORBIDDEN_KEYS.has(key)) {
      throw new Error(`dsh-one-gateway: ${label} must not contain ${key}`)
    }
  }
}

function rejectUnknownKeys(object, allowed, label) {
  for (const key of Object.keys(object)) {
    if (!allowed.has(key)) throw new Error(`dsh-one-gateway: unsupported ${label} key: ${key}`)
  }
}

/** An opaque setup-only proof used solely by the loopback readiness endpoint. */
export function parseActivationToken(value) {
  if (typeof value !== 'string' || !/^[A-Za-z0-9_-]{43}$/.test(value)) {
    throw new Error('dsh-one-gateway: activationToken must be a 32-byte base64url token generated by setup')
  }
  return value
}

export function normalizeExternalOrigin(value, { requireTailscaleDns = false, rejectQuickTunnel = false } = {}) {
  let url
  try {
    url = new URL(value)
  } catch {
    throw new Error('dsh-one-gateway: externalOrigin must be an absolute HTTPS URL')
  }
  if (
    url.protocol !== 'https:' || url.username || url.password ||
    url.pathname !== '/' || url.search || url.hash
  ) {
    throw new Error('dsh-one-gateway: externalOrigin must be an origin-only HTTPS URL')
  }
  if (url.hostname.length === 0) {
    throw new Error('dsh-one-gateway: externalOrigin hostname is missing')
  }
  if (requireTailscaleDns && (!url.hostname.endsWith('.ts.net') || url.hostname === '.ts.net')) {
    throw new Error('dsh-one-gateway: tailscale-serve externalOrigin must be an origin-only HTTPS *.ts.net URL')
  }
  if (rejectQuickTunnel && (url.hostname.endsWith('.trycloudflare.com') || url.hostname === 'trycloudflare.com')) {
    throw new Error('dsh-one-gateway: cloudflare-access does not support Cloudflare quick tunnels')
  }
  return url.origin
}

export function normalizeHttpsOrigin(value, label) {
  let url
  try {
    url = new URL(value)
  } catch {
    throw new Error(`dsh-one-gateway: ${label} must be an absolute HTTPS URL`)
  }
  if (
    url.protocol !== 'https:' || url.username || url.password ||
    url.pathname !== '/' || url.search || url.hash || !url.hostname
  ) {
    throw new Error(`dsh-one-gateway: ${label} must be an origin-only HTTPS URL`)
  }
  return url.origin
}

export function parseTrustedPrincipals(values, expectedNamespace) {
  if (!Array.isArray(values) || values.length === 0) {
    throw new Error('dsh-one-gateway: trustedPrincipals must contain at least one namespaced principal')
  }
  if (values.length > MAX_TRUSTED_PRINCIPALS) {
    throw new Error(`dsh-one-gateway: trustedPrincipals cannot contain more than ${MAX_TRUSTED_PRINCIPALS} entries`)
  }
  const prefix = `${expectedNamespace}:`
  const principals = []
  const seen = new Set()
  for (const value of values) {
    if (typeof value !== 'string' || value.length < prefix.length + 1 || value.length > MAX_PRINCIPAL_LENGTH || value.trim() !== value || !/^[\x21-\x7e]+$/.test(value)) {
      throw new Error('dsh-one-gateway: each trusted principal must be a trimmed printable ASCII namespaced string')
    }
    if (!value.startsWith(prefix) || value.slice(prefix.length).length === 0) {
      throw new Error(`dsh-one-gateway: trustedPrincipals for this auth mode must use the ${prefix} namespace`)
    }
    if (seen.has(value)) {
      throw new Error('dsh-one-gateway: trustedPrincipals must not contain duplicates')
    }
    seen.add(value)
    principals.push(value)
  }
  return principals
}

function parseRouteManagement(value, { allowed }) {
  if (!allowed.includes(value)) {
    throw new Error(`dsh-one-gateway: routeManagement must be one of: ${allowed.join(', ')}`)
  }
  return value
}

function parseTailscaleProvider(provider) {
  rejectUnknownKeys(provider, TAILSCALE_PROVIDER_KEYS, 'provider')
  if (typeof provider.routeManagement !== 'string') {
    throw new Error('dsh-one-gateway: provider.routeManagement is required')
  }
  return Object.freeze({
    type: PROVIDER_TAILSCALE,
    routeManagement: parseRouteManagement(provider.routeManagement, { allowed: [ROUTE_ENSURE, ROUTE_VERIFY_ONLY] }),
  })
}

function parseCloudflareProvider(provider) {
  rejectUnknownKeys(provider, CLOUDFLARE_PROVIDER_KEYS, 'provider')
  if (typeof provider.routeManagement !== 'string') {
    throw new Error('dsh-one-gateway: provider.routeManagement is required')
  }
  const routeManagement = parseRouteManagement(provider.routeManagement, { allowed: [ROUTE_VERIFY_ONLY] })
  if (typeof provider.teamOrigin !== 'string' || provider.teamOrigin.length === 0) {
    throw new Error('dsh-one-gateway: cloudflare-access requires teamOrigin')
  }
  if (typeof provider.applicationAudience !== 'string' || provider.applicationAudience.length === 0 || provider.applicationAudience.length > 256) {
    throw new Error('dsh-one-gateway: cloudflare-access requires a non-empty applicationAudience')
  }
  if (provider.applicationAudience.trim() !== provider.applicationAudience || !/^[\x21-\x7e]+$/.test(provider.applicationAudience)) {
    throw new Error('dsh-one-gateway: applicationAudience must be a trimmed printable ASCII string')
  }
  const teamOrigin = normalizeHttpsOrigin(provider.teamOrigin, 'teamOrigin')
  return Object.freeze({
    type: PROVIDER_CLOUDFLARE,
    routeManagement,
    teamOrigin,
    applicationAudience: provider.applicationAudience,
    jwksPath: '/cdn-cgi/access/certs',
  })
}

function parseProvider(provider) {
  if (!isRecord(provider)) throw new Error('dsh-one-gateway: provider must be an object')
  rejectForbiddenKeys(provider, 'provider')
  if (provider.type === PROVIDER_EASYTIER) {
    throw new Error('dsh-one-gateway: provider type easytier is not supported in v1; the adapter is deferred until overlay-only bind and post-verification evidence exists')
  }
  if (provider.type === PROVIDER_TAILSCALE) return parseTailscaleProvider(provider)
  if (provider.type === PROVIDER_CLOUDFLARE) return parseCloudflareProvider(provider)
  throw new Error('dsh-one-gateway: provider.type must be tailscale-serve or cloudflare-access')
}

function parseCredentialStorePath(value) {
  if (typeof value !== 'string' || value.length === 0) {
    throw new Error('dsh-one-gateway: credentialStorePath is required for gateway-credential')
  }
  if (!value.startsWith('/') || value.includes('\\') || value.includes('\0') || value.includes('..')) {
    throw new Error('dsh-one-gateway: credentialStorePath must be an absolute path')
  }
  return value
}

function parseAuth(auth, expectedMode, expectedNamespace) {
  if (!isRecord(auth)) throw new Error('dsh-one-gateway: auth must be an object')
  rejectForbiddenKeys(auth, 'auth')
  if (auth.mode !== expectedMode) {
    throw new Error(`dsh-one-gateway: auth.mode must be ${expectedMode} for this provider`)
  }
  const allowed = auth.mode === AUTH_GATEWAY_CREDENTIAL ? AUTH_CREDENTIAL_KEYS : AUTH_COMMON_KEYS
  rejectUnknownKeys(auth, allowed, 'auth')
  const trustedPrincipals = Object.freeze(parseTrustedPrincipals(auth.trustedPrincipals, expectedNamespace))
  if (auth.mode === AUTH_GATEWAY_CREDENTIAL) {
    return Object.freeze({
      mode: AUTH_GATEWAY_CREDENTIAL,
      trustedPrincipals,
      credentialStorePath: parseCredentialStorePath(auth.credentialStorePath),
    })
  }
  if (auth.mode === AUTH_TRUSTED_HEADER) {
    return Object.freeze({ mode: AUTH_TRUSTED_HEADER, trustedPrincipals })
  }
  if (auth.mode === AUTH_SIGNED_JWT) {
    return Object.freeze({ mode: AUTH_SIGNED_JWT, trustedPrincipals })
  }
  throw new Error('dsh-one-gateway: unsupported auth.mode')
}

/**
 * The only public configuration accepted by an enabled instance. Fixed
 * listener/upstream values prevent a profile typo from widening its ingress.
 */
export function assertSafeConfig(input) {
  const config = structuredClone(input ?? {})
  if (config.enabled !== true) return { enabled: false }
  rejectForbiddenKeys(config, 'config')
  rejectUnknownKeys(config, ENABLED_KEYS, 'configuration')
  if (typeof config.externalOrigin !== 'string' || config.externalOrigin.length === 0) {
    throw new Error('dsh-one-gateway: externalOrigin is required when enabled')
  }
  const provider = parseProvider(config.provider)
  const compatibility = COMPATIBILITY[provider.type]
  if (!compatibility) throw new Error('dsh-one-gateway: provider is not in the v1 compatibility matrix')
  const requireTailscaleDns = provider.type === PROVIDER_TAILSCALE
  const rejectQuickTunnel = provider.type === PROVIDER_CLOUDFLARE
  const externalOrigin = normalizeExternalOrigin(config.externalOrigin, { requireTailscaleDns, rejectQuickTunnel })
  const auth = parseAuth(config.auth, compatibility.authMode, compatibility.principalNamespace)
  const activationToken = config.activationToken === undefined ? undefined : parseActivationToken(config.activationToken)
  return Object.freeze({
    enabled: true,
    externalOrigin,
    provider,
    auth,
    identity: Object.freeze({ ...compatibility }),
    listenHost: GATEWAY_HOST,
    listenPort: GATEWAY_PORT,
    upstream: Object.freeze({ host: UPSTREAM_HOST, port: UPSTREAM_PORT }),
    httpsPort: httpsPortFromOrigin(externalOrigin),
    ...(activationToken === undefined ? {} : { activationToken }),
  })
}

export function readinessRequestTarget(token) {
  return `${READINESS_PATH}?token=${parseActivationToken(token)}`
}
